Repository mesg-foundation/engine, pull requests merged in 2018-10, with the labels that each got.

#510 update ecosystem menu for documentation
  docs/.vuepress/config.yml
  docs/.vuepress/style.styl
Labels: documentation

#512 Add sitemap on the documentation
  package-lock.json
  package.json
Labels: documentation

#511 Update tutorial page in documentation
  docs/.vuepress/components/card-link.vue
  docs/.vuepress/config.yml
  docs/tutorials/README.md
  docs/tutorials/erc20-transfer-notifications/README.md
  docs/tutorials/erc20-transfer-notifications/email-notification-one-erc20-transfer/.gitignore
  docs/tutorials/erc20-transfer-notifications/email-notification-one-erc20-transfer/index.js
  docs/tutorials/erc20-transfer-notifications/email-notification-one-erc20-transfer/package-lock.json
  docs/tutorials/erc20-transfer-notifications/email-notification-one-erc20-transfer/package.json
  docs/tutorials/erc20-transfer-notifications/listen-for-transfers-of-an-ethereum-erc20-token.md
  docs/tutorials/erc20-transfer-notifications/listen-to-transfer-of-ethereum-erc20-token/.mesgignore
  docs/tutorials/erc20-transfer-notifications/listen-to-transfer-of-ethereum-erc20-token/Dockerfile
  docs/tutorials/erc20-transfer-notifications/listen-to-transfer-of-ethereum-erc20-token/erc20-abi.json
  docs/tutorials/erc20-transfer-notifications/listen-to-transfer-of-ethereum-erc20-token/index.js
  docs/tutorials/erc20-transfer-notifications/listen-to-transfer-of-ethereum-erc20-token/mesg.yml
  docs/tutorials/erc20-transfer-notifications/listen-to-transfer-of-ethereum-erc20-token/package-lock.json
  docs/tutorials/erc20-transfer-notifications/listen-to-transfer-of-ethereum-erc20-token/package.json
  docs/tutorials/erc20-transfer-notifications/receive-email-when-there-is-an-erc20-transfer.md
  docs/tutorials/erc20-transfer-notifications/send-email-with-sendgrid/Dockerfile
  docs/tutorials/erc20-transfer-notifications/send-email-with-sendgrid/index.js
  docs/tutorials/erc20-transfer-notifications/send-email-with-sendgrid/mesg.yml
  docs/tutorials/erc20-transfer-notifications/send-email-with-sendgrid/package-lock.json
  docs/tutorials/erc20-transfer-notifications/send-email-with-sendgrid/package.json
  docs/tutorials/erc20-transfer-notifications/send-email-with-sendgrid/test.json
  docs/tutorials/erc20-transfer-notifications/send-emails-with-sendgrid.md
Labels: documentation

#506 full unit test coverage for service package
  api/api.go
  container/build.go
  container/container.go
  container/mocks/Container.go
  container/namespace.go
  container/network.go
  container/service.go
  container/service_options.go
  container/shared_network.go
  container/shared_network_integration_test.go
  container/task.go
  container/wait.go
  daemon/init.go
  scripts/build-mocks.sh
  service/dependency.go
  service/dependency_test.go
  service/logs_integration_test.go
  service/service.go
  service/service_integration_test.go
  service/service_test.go
  service/start.go
  service/start_integration_test.go
  service/start_test.go
  service/status.go
  service/status_integration_test.go
  service/status_test.go
  service/stop.go
  service/stop_integration_test.go
  service/stop_test.go
Labels: unit testing

#509 Add forum link in the doc
  CONTRIBUTING.md
  README.md
Labels: documentation

#534 Fix: Add network aliases
  container/service_options.go
  container/service_options_test.go
  daemon/start.go
  daemon/start_test.go
  docs/guide/service/dockerize-the-service.md
  service/start.go
  service/start_test.go
Labels: bug

#524 fix sync issue on status send chans and sync issue on gRPC deploy stream sends
  api/deploy.go
  commands/service_deploy.go
  commands/service_dev.go
  interface/grpc/core/deploy.go
  service/service.go
Labels: bugfix

#543 organize initialization of gRPC server and core
  core/main.go
  interface/grpc/core/core_test.go
  interface/grpc/core/type.go
  interface/grpc/server.go
  interface/grpc/server_test.go
  interface/grpc/service/service_test.go
  interface/grpc/service/type.go
Labels: enhancement
