Repository mesg-foundation/engine, pull requests merged in 2018-05, with the labels that each got.

#117 add MESG endpoint to the service container
  .dockerignore
  Dockerfile
  README.md
  api/server.go
  api/server_test.go
  cmd/root.go
  cmd/service/test.go
  config/api.go
  config/directory.go
  mesg-daemon
  service/start.go
Labels: help wanted

#146 Add Database package
  .circleci/config.yml
  database/services/all.go
  database/services/all_test.go
  database/services/db.go
  database/services/db_test.go
  database/services/delete.go
  database/services/delete_test.go
  database/services/get.go
  database/services/get_test.go
  database/services/save.go
  database/services/save_test.go
Labels: Application

#178 fix issue when sharing folder between containers
  daemon/start.go
  daemon/start_test.go
Labels: Application / Service, bug
