Repository mesg-foundation/engine, pull requests merged in 2018-06, with the labels that each got.

#185 Fix daemon logs
  .dockerignore
  CHANGELOG.md
  cmd/daemon/logs.go
Labels: application / service, bug

#181 Make start and stop functions blocking
  .circleci/config.yml
  CHANGELOG.md
  cmd/daemon/start.go
  cmd/daemon/stop.go
  cmd/service/list.go
  cmd/service/start.go
  cmd/service/stop.go
  cmd/service/test.go
  cmd/utils/spinner.go
  container/container.go
  container/container_test.go
  container/service_options.go
  container/service_options_test.go
  daemon/start.go
  daemon/start_test.go
  daemon/stop.go
  service/start.go
  service/start_test.go
  service/stop.go
Labels: application / service, enhancement

#179 API filter on events and results
  CHANGELOG.md
  api/core/api.pb.go
  api/core/api.proto
  api/core/listen_event.go
  api/core/listen_event_test.go
  api/core/listen_result.go
  api/core/listen_result_test.go
  cmd/service/test.go
  docs/cli/mesg-cli.md
  docs/cli/mesg-cli_daemon.md
  docs/cli/mesg-core.md
  docs/cli/mesg-core_daemon.md
  docs/cli/mesg-core_daemon_logs.md
  docs/cli/mesg-core_daemon_start.md
  docs/cli/mesg-core_daemon_status.md
  docs/cli/mesg-core_daemon_stop.md
  docs/cli/mesg-core_service.md
  docs/cli/mesg-core_service_delete.md
  docs/cli/mesg-core_service_deploy.md
  docs/cli/mesg-core_service_detail.md
  docs/cli/mesg-core_service_list.md
  docs/cli/mesg-core_service_start.md
  docs/cli/mesg-core_service_stop.md
  docs/cli/mesg-core_service_test.md
  utils/array/include.go
  utils/array/include_test.go
Labels: application, enhancement

#190 Possibility to fetch deploy a service from git
  CHANGELOG.md
  Dockerfile
  cmd/service/deploy.go
  cmd/service/test.go
  cmd/service/utils.go
  cmd/service/utils_test.go
Labels: application / service, enhancement

#184 [WIP] update readme
  README.md
  codecov.yml
  logo.svg
Labels: application

#208 Fix services image
  .circleci/config.yml
  service/start.go
  service/start_test.go
Labels: application / service, bug

#212 Use and inject hash to identify service
  .codacy.yml
  CHANGELOG.md
  api/service/api.pb.go
  api/service/api.proto
  api/service/emit_event.go
  api/service/emit_event_test.go
  api/service/listen_task.go
  service/namespace.go
  service/namespace_test.go
  service/start.go
  service/start_test.go
Labels: application / service

#226 Remove error parameter from all gRPC api
  api/core/api.pb.go
  api/core/api.proto
  api/service/api.pb.go
  api/service/api.proto
  api/service/submit_result.go
Labels: breaking change

#227 Remove ExecutionID from SubmitResultReply
  api/service/api.pb.go
  api/service/api.proto
  api/service/submit_result.go
Labels: breaking change

#234 Merge the status and list command
  CHANGELOG.md
  cmd/service.go
  cmd/service/list.go
  cmd/service/list_test.go
  cmd/service/status.go
  service/status.go
Labels: application, enhancement

#235 Add core api
  CHANGELOG.md
  api/core/api.pb.go
  api/core/api.proto
  api/core/get_service.go
  api/core/get_service_test.go
  api/core/list_services.go
  api/core/list_services_test.go
Labels: application

#236 Update cli with new api
  CHANGELOG.md
  cmd/service/delete.go
  cmd/service/detail.go
  cmd/service/list.go
  cmd/service/logs.go
  cmd/service/pause.go
  cmd/service/resume.go
Labels: application

#233 Add logs to test command
  CHANGELOG.md
  cmd/service/logs.go
  cmd/service/test.go
  docs/cli/mesg-core.md
  docs/cli/mesg-core_logs.md
  docs/cli/mesg-core_service.md
  docs/cli/mesg-core_service_delete.md
  docs/cli/mesg-core_service_deploy.md
  docs/cli/mesg-core_service_logs.md
  docs/cli/mesg-core_service_test.md
  docs/cli/mesg-core_start.md
  docs/cli/mesg-core_status.md
  docs/cli/mesg-core_stop.md
Labels: application

#260 Revert "Add commit sha to version of the release-dev cli"
  .circleci/config.yml
  scripts/build-cli.sh
Labels: bug

#257 Template for the service init
  CHANGELOG.md
  cmd/service/init.go
  cmd/service/init_test.go
  cmd/service/utils.go
  cmd/service/utils_test.go
Labels: application / service
