Repository mesg-foundation/engine, pull requests merged in 2018-08, with the labels that each got.

#313 Grammar update api.proto
  api/core/api.proto
Labels: in progress

#315 Update test command in the documentation
  docs/guide/service/test-new.md
  docs/guide/service/test.md
Labels: in progress

#316 remove the test service when the dev command ends
  cmd/service/dev.go
Labels: application, enhancement, in progress

#319 Krhubert/utils
  utils/array/include.go
  utils/hash/hash.go
Labels: in progress

#327 Krhubert/config
  config/api.go
  config/api_test.go
  config/config.go
Labels: in progress

#331 Krhubert/api server
  api/server.go
Labels: in progress

#322 Krhubert/execution
  execution/complete.go
  execution/complete_test.go
  execution/create.go
  execution/create_test.go
  execution/error.go
  execution/execute.go
  execution/execute_test.go
  execution/state_test.go
  execution/type.go
Labels: in progress

#325 Krhubert/daemon
  daemon/const.go
  daemon/logs.go
  daemon/start.go
  daemon/status.go
  daemon/status_test.go
  daemon/stop.go
Labels: in progress

#323 Krhubert/event
  event/event.go
  event/event_test.go
  event/publish.go
  event/type.go
Labels: in progress

#330 Krhubert/api service
  api/service/emit_event.go
  api/service/emit_event_test.go
  api/service/error.go
  api/service/listen_task.go
  api/service/submit_result.go
  api/service/submit_result_test.go
  api/service/type.go
Labels: in progress

#326 Krhubert/container
  container/build.go
  container/client.go
  container/container.go
  container/namespace.go
  container/network.go
  container/service.go
  container/service_options.go
  container/service_options_test.go
  container/service_test.go
  container/shared_network.go
  container/shared_network_test.go
  container/task.go
  container/type.go
  container/wait.go
Labels: in progress

#334 Revert "Krhubert/container"
  container/build.go
  container/client.go
  container/container.go
  container/namespace.go
  container/network.go
  container/service.go
  container/service_options.go
  container/service_options_test.go
  container/service_test.go
  container/shared_network.go
  container/shared_network_test.go
  container/task.go
  container/type.go
  container/wait.go
Labels: in progress

#324 Krhubert/database
  database/services/all.go
  database/services/db.go
  database/services/db_test.go
  database/services/delete.go
  database/services/errors.go
  database/services/get.go
  database/services/save.go
Labels: in progress

#336 Krhubert/container
  container/build.go
  container/client.go
  container/container.go
  container/namespace.go
  container/network.go
  container/service.go
  container/service_options.go
  container/service_options_test.go
  container/service_test.go
  container/shared_network.go
  container/shared_network_test.go
  container/task.go
  container/type.go
  container/wait.go
Labels: in progress

#338 fix missing error returned
  container/shared_network.go
Labels: in progress

#333 Krhubert/api client
  api/client/task.go
  api/client/wokflow.go
  api/core/get_service.go
  api/core/list_services.go
  api/core/listen_result.go
  api/core/stop.go
Labels: in progress

#345 Krhubert/core v2
  api/core/delete.go
  api/core/delete_test.go
  api/core/deploy.go
  api/core/deploy_test.go
  api/core/execute.go
  api/core/execute_test.go
  api/core/get_service.go
  api/core/get_service_test.go
  api/core/list_services.go
  api/core/listen_event.go
  api/core/listen_event_test.go
  api/core/listen_result.go
  api/core/listen_result_test.go
  api/core/start.go
  api/core/start_test.go
  api/core/stop.go
  api/core/stop_test.go
  api/core/type.go
Labels: to review

#320 Krhubert/service
  service/dependency.go
  service/dependency_test.go
  service/error.go
  service/hash.go
  service/importer/assets/schema.go
  service/importer/docker_file.go
  service/importer/errors.go
  service/importer/import.go
  service/importer/service_file.go
  service/importer/validation.go
  service/importer/validation_result.go
  service/logs.go
  service/logs_test.go
  service/namespace.go
  service/namespace_test.go
  service/start.go
  service/start_test.go
  service/status.go
  service/status_test.go
  service/stop.go
  service/stop_test.go
  service/validation.go
  service/validation_test.go
Labels: to review

#340 Feature/container: new Container type & unit tests
  cmd/service/utils.go
  container/build.go
  container/build_integration_test.go
  container/build_test.go
  container/client.go
  container/client_test.go
  container/container.go
  container/container_integration_test.go
  container/container_test.go
  container/dockertest/client.go
  container/dockertest/error.go
  container/dockertest/error_test.go
  container/dockertest/requests.go
  container/dockertest/responses.go
  container/dockertest/testing.go
  container/dockertest/testing_test.go
  container/network.go
  container/network_integration_test.go
  container/network_test.go
  container/service.go
  container/service_integration_test.go
  container/service_test.go
  container/shared_network.go
  container/shared_network_integration_test.go
  container/shared_network_test.go
  container/task.go
  container/task_integration_test.go
  container/task_test.go
  container/wait.go
  container/wait_integration_test.go
  container/wait_test.go
  daemon/init.go
  daemon/logs.go
  daemon/start.go
  daemon/start_test.go
  daemon/status.go
  daemon/stop.go
  service/init.go
  service/logs.go
  service/start.go
  service/start_test.go
  service/status.go
  service/stop.go
  service/stop_test.go
Labels: high priority, refactoring, unit testing

#317 Return an error when trying to execute a task on a non running service
  CHANGELOG.md
  api/core/error.go
  api/core/error_test.go
  api/core/execute.go
  api/core/execute_test.go
  cmd/service/stop.go
Labels: API, bug

#369 fix button position on documentation
  docs/.vuepress/style.styl
Labels: bug

#380 return err if dependency.Start() fails in service.Start()
  service/start.go
Labels: bug

#402 service: update error types to be more logicless, simplify validations
  .circleci/config.yml
  api/emit_event_emitter.go
  api/execute_executor.go
  api/execute_executor_test.go
  container/service_integration_test.go
  container/service_options_test.go
  container/service_test.go
  daemon/start_test.go
  event/event.go
  event/event_test.go
  execution/complete.go
  execution/complete_test.go
  execution/create.go
  execution/create_test.go
  interface/grpc/core/execute_test.go
  interface/grpc/service/emit_event_test.go
  interface/grpc/service/submit_result_test.go
  service-test/task/mesg.yml
  service/cast.go
  service/dependency_test.go
  service/error.go
  service/error_test.go
  service/logs_test.go
  service/namespace_test.go
  service/start_test.go
  service/status_test.go
  service/stop_test.go
  service/validation.go
  service/validation_test.go
Labels: refactoring
