Repository mesg-foundation/engine, pull requests merged in 2019-08, with the labels that each got.

#1201 Multi step workflow
  execution/execution.go
  execution/execution_test.go
  protobuf/types/execution.pb.go
  protobuf/types/execution.proto
  protobuf/types/service.pb.go
  protobuf/types/service.proto
  sdk/execution/execution.go
  sdk/execution/execution_test.go
  sdk/service/service.go
  server/grpc/api/execution.go
  server/grpc/api/execution_test.go
  server/grpc/api/mapping.go
  service/type.go
  workflow/workflow.go
Labels: enhancement

#1204 Move workflow to its own database/api
  config/config.go
  core/main.go
  database/workflow_db.go
  engine/workflow.go
  protobuf/api/service.pb.go
  protobuf/api/service.proto
  protobuf/api/workflow.pb.go
  protobuf/api/workflow.proto
  protobuf/types/service.pb.go
  protobuf/types/service.proto
  protobuf/types/workflow.pb.go
  protobuf/types/workflow.proto
  scripts/build-proto.sh
  sdk/execution/execution.go
  sdk/execution/execution_test.go
  sdk/sdk.go
  sdk/service/service.go
  sdk/workflow/workflow.go
  server/grpc/api/execution_test.go
  server/grpc/api/mapping.go
  server/grpc/api/service.go
  server/grpc/api/workflow.go
  server/grpc/core/test_test.go
  server/grpc/server.go
  service/type.go
  service/workflow.go
  workflow/type.go
  workflow/workflow.go
  workflow/workflow_test.go
Labels: enhancement, waiting dependent pr

#1210 Improve regex used in dev script
  dev
Labels: enhancement

#1217 Fix dev script
  dev
Labels: bug

#1213 Print file and function name on logging
  core/main.go
  go.mod
  go.sum
  server/grpc/server.go
Labels: enhancement

#1215 Remove unused variable and improve error handling of config.setupServices function
  config/config.go
  config/services.go
Labels: refactoring

#1211 Cosmos integration
  .dockerignore
  .gitignore
  config/config.go
  core/main.go
  dev
  go.mod
  go.sum
  internal/tools/gen_tm_identity.go
  logger/tendermint.go
  tendermint/app/app.go
  tendermint/node.go
Labels: enhancement

#1218 Set tm config in config package and pass it on node creation
  config/config.go
  config/config_test.go
  core/main.go
  dev
  tendermint/node.go
Labels: refactoring

#1209 Workflow graph structure
  execution/execution.go
  execution/execution_test.go
  protobuf/api/workflow.pb.go
  protobuf/api/workflow.proto
  protobuf/types/execution.pb.go
  protobuf/types/execution.proto
  protobuf/types/workflow.pb.go
  protobuf/types/workflow.proto
  scheduler/scheduler.go
  sdk/execution/execution.go
  sdk/execution/execution_test.go
  sdk/workflow/workflow.go
  server/grpc/api/execution.go
  server/grpc/api/execution_test.go
  server/grpc/api/workflow.go
  workflow/type.go
  workflow/workflow.go
Labels: enhancement

#1214 Create struct service.Configuration
  config/services.go
  sdk/instance/helpers.go
  sdk/instance/start.go
  sdk/instance/stop.go
  sdk/instance/volume.go
  sdk/service/service.go
  server/grpc/api/mapping.go
  service/type.go
  service/validator/validator.go
Labels: refactoring

#1220 Remove regexp network filter from dev script
  dev
Labels: bug

#1224 Only restore go cache from the exact same go.sum file in CircleCI
  .circleci/config.yml
Labels: dependencies

#1226 update Cosmos to v0.36
  go.mod
  go.sum
  tendermint/app/app.go
  tendermint/node.go
Labels: enhancement

#1219 Add cosmos modules
  config/config.go
  config/config_test.go
  core/main.go
  dev
  go.mod
  go.sum
  internal/tools/gen_cosmos_account/main.go
  internal/tools/gen_tm_identity/main.go
  tendermint/app/app.go
  tendermint/keybase.go
  tendermint/node.go
Labels: enhancement

#1227 Possibility to enable/disable network when running the engine
  core/main.go
  dev
Labels: enhancement

#1223 Workflow validation
  sdk/workflow/workflow.go
  workflow/algorithm.go
  workflow/algorithm_test.go
  workflow/workflow.go
  workflow/workflow_test.go
Labels: enhancement

#1230 Remove git related package
  go.mod
  go.sum
  x/xgit/repository.go
  x/xgit/repository_test.go
Labels: refactoring

#1229 Remove trigger type for workflows
  protobuf/api/event.pb.go
  protobuf/api/execution.pb.go
  protobuf/api/instance.pb.go
  protobuf/api/service.pb.go
  protobuf/api/workflow.pb.go
  protobuf/coreapi/api.pb.go
  protobuf/types/workflow.pb.go
  protobuf/types/workflow.proto
  scheduler/scheduler.go
  server/grpc/api/workflow.go
  workflow/type.go
  workflow/workflow.go
  workflow/workflow_test.go
Labels: enhancement

#1239 Simplify function initDependencies in main.go
  core/main.go
Labels: dependencies, refactoring

#1242 Add missing db cleanup in grpc core test
  server/grpc/core/test_test.go
Labels: tests

#1241 Workflow input resolution
  protobuf/types/workflow.pb.go
  protobuf/types/workflow.proto
  scheduler/scheduler.go
  server/grpc/api/workflow.go
  workflow/algorithm.go
  workflow/type.go
  workflow/workflow.go
  workflow/workflow_test.go
Labels: enhancement, release:add

#1243 Add store package
  database/store/cosmos.go
  database/store/interface.go
  database/store/leveldb.go
Labels: experimental, refactoring

#1254 Remove database ErrNotFound. Introduce Database Exist function.
  database/instance_db.go
  database/service_db.go
  database/service_db_test.go
  database/store/cosmos.go
  database/store/interface.go
  database/store/leveldb.go
  database/workflow_db.go
  sdk/instance/instance.go
Labels: refactoring

#1244 Update service db to use store
  core/main.go
  database/service_db.go
  database/service_db_test.go
  sdk/execution/execution_test.go
  sdk/sdk.go
  sdk/service/service.go
  server/grpc/core/test_test.go
Labels: experimental, release:change

#1248 Add Cosmos helpers
  core/main.go
  cosmos/app.go
  cosmos/initModules.go
  cosmos/keybase.go
  cosmos/module.go
  cosmos/node.go
  cosmos/txbuilder.go
  go.mod
  go.sum
  tendermint/app/app.go
Labels: experimental, release:add

#1257 Recover from panic in cosmos store
  database/store/cosmos.go
Labels: bug

#1255 Create tendermint client
  cosmos/client/client.go
Labels: enhancement, experimental

#1249 SDK loads the App modules
  core/main.go
  go.mod
  go.sum
  sdk/module.go
  sdk/sdk.go
  server/grpc/api/execution_test.go
  server/grpc/core/test_test.go
Labels: experimental

#1250 Transform service sdk to accept cosmos service step 1
  sdk/event/event.go
  sdk/execution/execution.go
  sdk/execution/execution_test.go
  sdk/instance/instance.go
  sdk/sdk.go
  sdk/service/deprecated.go
  sdk/service/type.go
Labels: experimental

#1252 Add service sdk cosmos version step 2
  core/main.go
  go.mod
  sdk/sdk.go
  sdk/service/deprecated.go
  sdk/service/module.go
  sdk/service/sdk.go
  sdk/service/utils.go
Labels: experimental, waiting dependent pr

#1260 Keep only one Service struct (the one generated from protobuf definition)
  Dockerfile.tools
  core/main.go
  database/service_db.go
  database/service_db_test.go
  go.mod
  hash/hash.go
  hash/hash_test.go
  protobuf/api/service.pb.go
  protobuf/api/service.proto
  protobuf/types/service.pb.go
  protobuf/types/service.proto
  scripts/build-proto.sh
  sdk/execution/execution_test.go
  sdk/instance/helpers.go
  sdk/instance/instance.go
  sdk/instance/start.go
  sdk/instance/volume.go
  sdk/service/utils.go
  server/grpc/api/mapping.go
  server/grpc/api/service.go
  service/error_test.go
  service/service.go
  service/service.pb.go
  service/service_test.go
  service/type.go
  service/validation.go
  service/validation_test.go
Labels: refactoring

#1269 Change service.proto package back to types
  protobuf/api/service.pb.go
  protobuf/api/service.proto
  protobuf/types/service.proto
  service/service.pb.go
Labels: refactoring

#1258 Pure graph implementation for the orchestration system
  protobuf/api/workflow.pb.go
  protobuf/api/workflow.proto
  protobuf/types/workflow.pb.go
  protobuf/types/workflow.proto
  scheduler/scheduler.go
  sdk/workflow/workflow.go
  server/grpc/api/workflow.go
  workflow/algorithm.go
  workflow/filter.go
  workflow/filter_test.go
  workflow/graph.go
  workflow/graph_test.go
  workflow/marshal.go
  workflow/marshal_test.go
  workflow/type.go
  workflow/workflow.go
  workflow/workflow_test.go
Labels: breaking change, enhancement

#1268 Make cosmos store iterator works the same way as goleveldb iterator
  database/store/cosmos.go
Labels: bug

#1270 Change proto hash type from string to bytes
  core/main.go
  database/service_db.go
  database/service_db_test.go
  hash/hash.go
  hash/hash_test.go
  protobuf/api/event.pb.go
  protobuf/api/event.proto
  protobuf/api/execution.pb.go
  protobuf/api/execution.proto
  protobuf/api/instance.pb.go
  protobuf/api/instance.proto
  protobuf/api/service.pb.go
  protobuf/api/service.proto
  protobuf/api/workflow.pb.go
  protobuf/api/workflow.proto
  protobuf/types/event.pb.go
  protobuf/types/event.proto
  protobuf/types/execution.pb.go
  protobuf/types/execution.proto
  protobuf/types/instance.pb.go
  protobuf/types/instance.proto
  protobuf/types/service.proto
  protobuf/types/workflow.pb.go
  protobuf/types/workflow.proto
  sdk/execution/execution_test.go
  sdk/instance/instance.go
  sdk/instance/start.go
  sdk/service/utils.go
  server/grpc/api/event.go
  server/grpc/api/execution.go
  server/grpc/api/execution_test.go
  server/grpc/api/instance.go
  server/grpc/api/service.go
  server/grpc/api/workflow.go
  service/service.pb.go
  workflow/marshal.go
Labels: breaking change, refactoring, release:change

#1274 Add filter support for the orchestrator
  filter/filter.go
  filter/filter_test.go
  go.mod
  protobuf/types/workflow.pb.go
  protobuf/types/workflow.proto
  scheduler/scheduler.go
  server/grpc/api/workflow.go
  workflow/filter.go
  workflow/filter_test.go
  workflow/type.go
  workflow/workflow.go
Labels: enhancement

#1278 Rename workflow to process
  config/config.go
  core/main.go
  database/process_db.go
  database/workflow_db.go
  execution/execution.go
  filter/filter.go
  orchestrator/orchestrator.go
  process/graph.go
  process/graph_test.go
  process/marshal.go
  process/marshal_test.go
  process/process.go
  process/process_test.go
  process/type.go
  protobuf/api/process.pb.go
  protobuf/api/process.proto
  protobuf/api/workflow.pb.go
  protobuf/api/workflow.proto
  protobuf/types/execution.pb.go
  protobuf/types/execution.proto
  protobuf/types/process.pb.go
  protobuf/types/process.proto
  protobuf/types/workflow.pb.go
  scripts/build-proto.sh
  sdk/execution/execution.go
  sdk/execution/execution_test.go
  sdk/process/process.go
  sdk/sdk.go
  sdk/workflow/workflow.go
  server/grpc/api/execution.go
  server/grpc/api/process.go
  server/grpc/api/workflow.go
  server/grpc/core/test_test.go
  server/grpc/server.go
Labels: breaking change, documentation, enhancement
