Repository mesg-foundation/engine, pull requests merged in 2019-09, with the labels that each got.

#1286 Fix marshal issue with process filter
  process/marshal.go
  process/marshal_test.go
Labels: bug

#1287 Update system services to work with latest gRPC API
  systemservices/ethwallet/client/client.go
  systemservices/ethwallet/compiled.json
  systemservices/ethwallet/go.mod
  systemservices/ethwallet/go.sum
  systemservices/marketplace/compiled.json
  systemservices/marketplace/package-lock.json
  systemservices/marketplace/package.json
Labels: bug

#1288 Fix that hash of info API were still in string instead of bytes.
  protobuf/coreapi/api.pb.go
  protobuf/coreapi/api.proto
  server/grpc/core/core.go
Labels: bug

#1284 Add test for both cosmos store and leveldb store
  database/store/cosmos_test.go
  database/store/leveldb_test.go
Labels: tests

#1290 Use gogo protobuf
  Dockerfile.tools
  protobuf/api/event.pb.go
  protobuf/api/execution.pb.go
  protobuf/api/instance.pb.go
  protobuf/api/process.pb.go
  protobuf/api/service.pb.go
  protobuf/convert/pbstruct.go
  protobuf/types/event.pb.go
  protobuf/types/execution.pb.go
  protobuf/types/instance.pb.go
  protobuf/types/process.pb.go
  scripts/build-proto.sh
  server/grpc/api/event.go
  server/grpc/api/execution.go
  service/service.pb.go
Labels: enhancement

#1291 Customize protobuf messages
  protobuf/api/event.pb.go
  protobuf/api/event.proto
  protobuf/api/execution.pb.go
  protobuf/api/execution.proto
  protobuf/api/instance.pb.go
  protobuf/api/instance.proto
  protobuf/api/process.pb.go
  protobuf/api/process.proto
  protobuf/api/service.pb.go
  protobuf/api/service.proto
  protobuf/types/event.pb.go
  protobuf/types/event.proto
  protobuf/types/execution.pb.go
  protobuf/types/execution.proto
  protobuf/types/instance.pb.go
  protobuf/types/instance.proto
  protobuf/types/process.pb.go
  protobuf/types/process.proto
Labels: refactoring

#1296 Remove and refactor rest protobuf types
  event/event.go
  event/event.pb.go
  execution/execution.go
  execution/execution.pb.go
  execution/execution_test.go
  filter/filter.go
  orchestrator/orchestrator.go
  process/filter.go
  process/filter_test.go
  process/graph.go
  process/graph_test.go
  process/marshal.go
  process/marshal_test.go
  process/process.go
  process/process.pb.go
  process/process_test.go
  process/type.go
  protobuf/api/event.pb.go
  protobuf/api/execution.pb.go
  protobuf/api/process.pb.go
  protobuf/types/event.proto
  protobuf/types/execution.proto
  protobuf/types/process.proto
  protobuf/types/service.proto
  scripts/build-proto.sh
  sdk/event/event.go
  sdk/execution/execution.go
  sdk/execution/execution_listener_test.go
  sdk/execution/execution_test.go
  sdk/process/process.go
  server/grpc/api/event.go
  server/grpc/api/execution.go
  server/grpc/api/execution_test.go
  server/grpc/api/process.go
  service/service.go
  service/service.pb.go
  service/service_test.go
Labels: refactoring

#1298 Replace cnf structhash with custom one
  go.mod
  go.sum
  hash/hash.go
  hash/structhash/structhash.go
  hash/structhash/structhash_test.go
Labels: refactoring

#1301 Update database path to ensure no issue on startup
  config/config.go
Labels: enhancement

#1310 Update gogo protobuf with fixed json and custom tags generation
  event/event.pb.go
  execution/execution.pb.go
  go.sum
  instance/instance.pb.go
  process/marshal.go
  process/process.pb.go
  protobuf/api/event.pb.go
  protobuf/api/execution.pb.go
  protobuf/api/instance.pb.go
  protobuf/api/process.pb.go
  protobuf/api/service.pb.go
  service/service.pb.go
Labels: bug

#1311 Use protobuf marshal/unmarshal in process database
  database/process_db.go
  database/process_db_test.go
  process/marshal.go
  process/marshal_test.go
  process/process.pb.go
  protobuf/types/process.proto
Labels: bug

#1312 Fix issue with execution update
  database/execution_db.go
  execution/execution.pb.go
  protobuf/types/execution.proto
  sdk/execution/execution_test.go
  server/grpc/api/execution_test.go
Labels: bug

#1305 Use CreateServiceRequest struct to create a service
  config/services.go
  sdk/service/deprecated.go
  sdk/service/module.go
  sdk/service/sdk.go
  sdk/service/type.go
  sdk/service/utils.go
  server/grpc/api/service.go
Labels: release:change

#1309 Do not convert proto.Struct to map in order to Validate it
  service/error.go
  service/error_test.go
  service/service.go
  service/service_parameter.go
  service/service_parameter_test.go
  service/service_test.go
  service/validation.go
  service/validation_test.go
Labels: refactoring

#1308 Simplify cosmos keybase by just creating a NewMnemonic helper
  cosmos/keybase.go
  cosmos/node.go
Labels: experimental

#1320 Use Structs in the orchestrator
  orchestrator/orchestrator.go
  process/filter.go
  process/filter_test.go
Labels: bug, waiting dependent pr

#1323 Remove unused docker api mocks
  utils/dockermock/mock.go
Labels: refactoring

#1327 Initialize fields for map processing
  orchestrator/orchestrator.go
Labels: bug

#1329 Calculate process hash based on the nodes
  process/process.pb.go
  protobuf/types/process.proto
Labels: bug

#1316 Add constant to process map
  orchestrator/orchestrator.go
  process/process.pb.go
  protobuf/types/process.proto
Labels: enhancement

#1322 Update golang to 1.13
  .circleci/config.yml
  .golangci.yml
  Dockerfile
  Dockerfile.tools
  go.mod
Labels: enhancement

#1331 Add --exp to dev command
  dev
Labels: enhancement, release:add

#1339 Fix hash.Unmarshal when using proto.Unmarshal
  database/process_db_test.go
  hash/hash.go
  hash/hash_test.go
Labels: release:fix

#1321 Only force hash calculation on interface containing struct
  hash/structhash/structhash.go
  hash/structhash/structhash_test.go
Labels: release:change

#1337 Namespace protobuf types/api
  event/event.pb.go
  execution/execution.pb.go
  instance/instance.pb.go
  process/process.pb.go
  protobuf/api/event.pb.go
  protobuf/api/event.proto
  protobuf/api/execution.pb.go
  protobuf/api/execution.proto
  protobuf/api/instance.pb.go
  protobuf/api/instance.proto
  protobuf/api/process.pb.go
  protobuf/api/process.proto
  protobuf/api/service.pb.go
  protobuf/api/service.proto
  protobuf/coreapi/api.pb.go
  protobuf/coreapi/api.proto
  protobuf/types/event.proto
  protobuf/types/execution.proto
  protobuf/types/instance.proto
  protobuf/types/process.proto
  protobuf/types/service.proto
  service/service.pb.go
Labels: breaking change, bug

#1342 Build and publish docker image with minor-only tag
  .circleci/config.yml
Labels: release:add

#1335 Remove plural form from instance list proto service
  protobuf/api/instance.pb.go
  protobuf/api/instance.proto
  server/grpc/api/instance.go
Labels: breaking change, refactoring

#1343 Add account sdk and its api
  account/account.pb.go
  core/main.go
  protobuf/api/account.pb.go
  protobuf/api/account.proto
  protobuf/types/account.proto
  scripts/build-proto.sh
  sdk/account/sdk.go
  sdk/sdk.go
  server/grpc/api/account.go
  server/grpc/server.go
Labels: release:add

#1317 Add tests for orchestrator
  orchestrator/mocks/EventSDK.go
  orchestrator/mocks/ExecutionSDK.go
  orchestrator/mocks/ProcessSDK.go
  orchestrator/orchestrator.go
  orchestrator/orchestrator_test.go
  orchestrator/type.go
  scripts/build-mocks.sh
Labels: release:add, tests

#1347 Update marketplace system service with latest mesg-js
  systemservices/marketplace/compiled.json
  systemservices/marketplace/package-lock.json
  systemservices/marketplace/package.json
Labels: dependencies

#1324 Update EthWallet service to latest gRPC API version
  protobuf/convert/pbstruct.go
  systemservices/ethwallet/Dockerfile
  systemservices/ethwallet/client/encoding.go
  systemservices/ethwallet/client/task_runner.go
  systemservices/ethwallet/compiled.json
  systemservices/ethwallet/ethwallet/create.go
  systemservices/ethwallet/ethwallet/delete.go
  systemservices/ethwallet/ethwallet/error.go
  systemservices/ethwallet/ethwallet/export.go
  systemservices/ethwallet/ethwallet/import.go
  systemservices/ethwallet/ethwallet/importFromPrivateKey.go
  systemservices/ethwallet/ethwallet/list.go
  systemservices/ethwallet/ethwallet/sign.go
  systemservices/ethwallet/ethwallet/type.go
  systemservices/ethwallet/go.mod
  systemservices/ethwallet/go.sum
  systemservices/ethwallet/mesg.yml
  systemservices/ethwallet/test-data/create.json
  systemservices/ethwallet/test-data/delete.json
  systemservices/ethwallet/test-data/export.json
  systemservices/ethwallet/test-data/import.json
  systemservices/ethwallet/test-data/importFromPrivateKey.json
  systemservices/ethwallet/test-data/sign.json
  systemservices/ethwallet/x/xgo-ethereum/xaccounts/accounts.go
Labels: release:change

#1355 Add credential using grpc metadata
  core/main.go
  execution/execution.pb.go
  protobuf/api/account.pb.go
  protobuf/api/account.proto
  sdk/service/deprecated.go
  sdk/service/sdk.go
  sdk/service/type.go
  server/grpc/api/account.go
  server/grpc/api/credential.go
  server/grpc/api/service.go
Labels: release:add

#1360 Use rsync to copy a file
  dev
Labels: bug

#1357 Update dependencies
  go.mod
  go.sum
Labels: dependencies

#1361 Refactor sdk deprecated and system services
  config/config.go
  config/config_test.go
  config/services.go
  core/main.go
  dev
  protobuf/coreapi/api.pb.go
  protobuf/coreapi/api.proto
  scripts/build-engine.sh
  sdk/execution/execution_test.go
  sdk/sdk.go
  sdk/service/deprecated.go
  sdk/service/sdk.go
  server/grpc/api/execution_test.go
  server/grpc/core/core.go
  server/grpc/core/core_integration_test.go
  server/grpc/core/test_test.go
  server/grpc/server.go
Labels: breaking change, refactoring

#1364 Remove core api
  protobuf/coreapi/api.pb.go
  protobuf/coreapi/api.proto
  scripts/build-proto.sh
  server/grpc/core/core.go
  server/grpc/server.go
Labels: breaking change, refactoring, waiting dependent pr

#1368 Add ownership SDK to support service ownership.
  Dockerfile.tools
  database/ownership_db.go
  database/ownership_test.go
  database/process_db.go
  database/service_db.go
  database/service_db_test.go
  ownership/codec.go
  ownership/ownership.pb.go
  protobuf/api/ownership.pb.go
  protobuf/api/ownership.proto
  protobuf/types/ownership.proto
  scripts/build-proto.sh
  sdk/backend.go
  sdk/ownership/backend.go
  sdk/ownership/sdk.go
  sdk/sdk.go
  sdk/service/backend.go
  sdk/service/msgs.go
  sdk/service/sdk.go
  sdk/service/utils.go
  server/grpc/api/ownership.go
  server/grpc/server.go
Labels: release:add

#1373 remove useless service-test folder
  service-test/env/Dockerfile
  service-test/env/mesg.yml
  service-test/event/Dockerfile
  service-test/event/index.js
  service-test/event/mesg.yml
  service-test/event/package.json
  service-test/invalid/empty
  service-test/task/Dockerfile
  service-test/task/index.js
  service-test/task/mesg.yml
  service-test/task/package.json
Labels: refactoring

#1375 Change service hash calculation
  core/main.go
  hash/dirhash/dirhash.go
  hash/dirhash/dirhash_test.go
  hash/dirhash/testdata/01/file
  hash/dirhash/testdata/01_mode/file
  hash/dirhash/testdata/02/dir/file
  hash/dirhash/testdata/03/symlink
  hash/dirhash/testdata/04/dir/file
  hash/dirhash/testdata/04/file
  hash/dirhash/testdata/04/symlink
  sdk/backend.go
  sdk/service/backend.go
  sdk/service/utils.go
Labels: breaking change, refactoring

#1371 Remove shared private info of the genesis account
  .gitignore
  config/config.go
  config/config_test.go
  core/main.go
  cosmos/node.go
  dev
  internal/tools/gen_cosmos_account/main.go
  internal/tools/gen_genesis_validator/main.go
Labels: enhancement

#1381 Remove service deletion
  protobuf/api/service.pb.go
  protobuf/api/service.proto
  sdk/service/backend.go
  sdk/service/msgs.go
  sdk/service/sdk.go
  sdk/service/type.go
  server/grpc/api/service.go
Labels: enhancement
