Repository mesg-foundation/engine, pull requests merged in 2019-12, with the labels that each got.

#1543 Add lock to cosmos lazy keybase
  cosmos/keybase.go
Labels: bug

#1546 Add map and filter orchestrator e2e tests
  e2e/orchestrator_event_filter_task_test.go
  e2e/orchestrator_event_map_task_map_task_test.go
  e2e/orchestrator_event_map_task_test.go
  e2e/orchestrator_event_task_test.go
  e2e/orchestrator_result_map_task_map_task_test.go
  e2e/orchestrator_result_task_test.go
  e2e/orchestrator_test.go
Labels: release:add, tests

#1547 Add nested data e2e tests
  e2e/api_test.go
  e2e/definition_test.go
  e2e/event_test.go
  e2e/execution_test.go
  e2e/orchestrator_event_task_complex_data_test.go
  e2e/orchestrator_test.go
  e2e/testdata/test-service-orchestrator/Dockerfile
  e2e/testdata/test-service-orchestrator/go.mod
  e2e/testdata/test-service-orchestrator/go.sum
  e2e/testdata/test-service-orchestrator/main.go
  e2e/testdata/test-service-orchestrator/mesg.yml
  e2e/testdata/test-service/main.go
  e2e/testdata/test-service/mesg.yml
Labels: release:add, tests

#1536 Move node.*.key into node and rename process.key to name
  database/process_db_test.go
  e2e/orchestrator_event_filter_task_test.go
  e2e/orchestrator_event_map_task_map_task_test.go
  e2e/orchestrator_event_map_task_test.go
  e2e/orchestrator_event_task_complex_data_test.go
  e2e/orchestrator_event_task_test.go
  e2e/orchestrator_result_map_task_map_task_test.go
  e2e/orchestrator_result_task_test.go
  e2e/process_test.go
  execution/execution.go
  execution/execution.pb.go
  orchestrator/orchestrator.go
  orchestrator/orchestrator_test.go
  process/graph.go
  process/graph_test.go
  process/process.go
  process/process.pb.go
  process/process_test.go
  protobuf/api/execution.pb.go
  protobuf/api/execution.proto
  protobuf/api/process.pb.go
  protobuf/api/process.proto
  protobuf/types/execution.proto
  protobuf/types/process.proto
  sdk/execution/backend.go
  server/grpc/api/process.go
Labels: breaking change, refactoring

#1527 Move process to cosmos network
  core/main.go
  database/process_db.go
  e2e/api_test.go
  e2e/ownership_test.go
  e2e/process_test.go
  e2e/service_test.go
  ownership/codec.go
  ownership/ownership.pb.go
  process/codec.go
  protobuf/api/process.pb.go
  protobuf/api/process.proto
  protobuf/types/ownership.proto
  sdk/backend.go
  sdk/execution/backend.go
  sdk/ownership/backend.go
  sdk/process/backend.go
  sdk/process/codec.go
  sdk/process/msgs.go
  sdk/process/process.go
  sdk/process/sdk.go
  sdk/sdk.go
  sdk/service/backend.go
  server/grpc/api/process.go
Labels: enhancement

#1540 Implement nested data on process map
  e2e/orchestrator_event_filter_task_test.go
  e2e/orchestrator_event_map_task_map_task_omplex_data_test.go
  e2e/orchestrator_event_map_task_map_task_test.go
  e2e/orchestrator_event_map_task_test.go
  e2e/orchestrator_event_task_complex_data_test.go
  e2e/orchestrator_event_task_test.go
  e2e/orchestrator_result_map_task_map_task_test.go
  e2e/orchestrator_result_task_test.go
  e2e/orchestrator_test.go
  orchestrator/orchestrator.go
  process/codec.go
  process/process.pb.go
  process/process_test.go
  protobuf/types/process.proto
Labels: breaking change, refactoring

#1545 Add path system to reference nested data in process
  e2e/definition_test.go
  e2e/orchestrator_filter_test.go
  e2e/orchestrator_map_const_test.go
  e2e/orchestrator_nested_data_test.go
  e2e/orchestrator_nested_map_test.go
  e2e/orchestrator_ref_nested_test.go
  e2e/orchestrator_ref_node_test.go
  e2e/orchestrator_ref_result_test.go
  e2e/orchestrator_ref_task_test.go
  e2e/orchestrator_test.go
  e2e/testdata/test-service/main.go
  e2e/testdata/test-service/mesg.yml
  orchestrator/orchestrator.go
  orchestrator/orchestrator_test.go
  process/codec.go
  process/process.pb.go
  process/process_test.go
  protobuf/types/process.proto
  scripts/run-e2e.sh
Labels: breaking change, enhancement

#1555 Remove account sdk and credential system
  account/account.pb.go
  core/main.go
  cosmos/client.go
  cosmos/genesis.go
  cosmos/genesis_test.go
  cosmos/keybase.go
  cosmos/keybase_test.go
  cosmos/txbuilder.go
  e2e/account_test.go
  e2e/api_test.go
  e2e/process_test.go
  e2e/service_test.go
  internal/tools/gen-genesis/main.go
  orchestrator/mocks/ExecutionSDK.go
  orchestrator/orchestrator.go
  orchestrator/orchestrator_test.go
  orchestrator/type.go
  protobuf/api/account.pb.go
  protobuf/api/account.proto
  protobuf/types/account.proto
  scripts/build-proto.sh
  sdk/account/sdk.go
  sdk/execution/sdk.go
  sdk/process/sdk.go
  sdk/runner/sdk.go
  sdk/sdk.go
  sdk/service/sdk.go
  server/grpc/api/account.go
  server/grpc/api/credential.go
  server/grpc/api/execution.go
  server/grpc/api/process.go
  server/grpc/api/runner.go
  server/grpc/api/service.go
  server/grpc/server.go
Labels: release:remove

#1556 Fix account sequence when signing multiple transactions
  cosmos/client.go
  e2e/execution_test.go
  e2e/testdata/e2e.config.yml
Labels: release:fix

#1575 Fix process owner test
  e2e/process_test.go
Labels: bug

#1579 Remove database config
  config/config.go
  config/config_test.go
Labels: refactoring
