Repository mesg-foundation/engine, pull requests merged in 2019-11, with the labels that each got.

#1451 Validate service nested object params
  service/validator/validator.go
Labels: bug, enhancement

#1473 Use filter in list instace api
  e2e/instance_test.go
  protobuf/api/instance.pb.go
  protobuf/api/instance.proto
  server/grpc/api/instance.go
Labels: breaking change, enhancement

#1477 Nullable instance filter
  server/grpc/api/instance.go
Labels: bug

#1474 Update golangci-lint to 1.21.0
  .circleci/config.yml
  .golangci.yml
Labels: enhancement

#1479 Return proper error code on e2e fail
  Makefile
  scripts/run-e2e.sh
Labels: bug

#1481 export MESG_PATH for e2e tests
  scripts/run-e2e.sh
Labels: bug

#1462 Use sequence number from cosmos auth module
  cosmos/client.go
  sdk/runner/sdk.go
  sdk/service/sdk.go
Labels: bug

#1483 Disable go test cache for e2e test
  scripts/run-e2e.sh
Labels: bug

#1488 Refactor database
  database/instance_db.go
  database/instance_db_test.go
  database/ownership_db.go
  database/ownership_db_test.go
  database/service_db.go
  database/service_db_test.go
  sdk/execution/execution_test.go
  sdk/instance/backend.go
  sdk/ownership/backend.go
  sdk/service/backend.go
Labels: refactoring

#1489 Add account.mnemonic in config
  config/config.go
  config/config_test.go
  core/main.go
  e2e/testdata/e2e.config.yml
Labels: enhancement

#1480 Use cosmos module to manage accounts and use single codec
  .golangci.yml
  codec/codec.go
  core/main.go
  cosmos/app.go
  cosmos/appfactory.go
  cosmos/client.go
  cosmos/genesis.go
  cosmos/genesis_test.go
  cosmos/module.go
  cosmos/txbuilder.go
  database/instance_db.go
  database/instance_db_test.go
  database/ownership_db.go
  database/ownership_db_test.go
  database/service_db.go
  database/service_db_test.go
  e2e/account_test.go
  go.mod
  internal/tools/gen-genesis/main.go
  ownership/codec.go
  sdk/backend.go
  sdk/execution/execution_test.go
  sdk/instance/backend.go
  sdk/ownership/backend.go
  sdk/ownership/sdk.go
  sdk/runner/backend.go
  sdk/runner/codec.go
  sdk/runner/msgs.go
  sdk/runner/sdk.go
  sdk/sdk.go
  sdk/service/backend.go
  sdk/service/codec.go
  sdk/service/msgs.go
  sdk/service/sdk.go
  server/grpc/api/execution_test.go
Labels: bug, enhancement

#1486 Fix 2 error string
  sdk/process/process.go
  sdk/service/backend.go
Labels: bug

#1499 Improve use of Value
  e2e/testdata/test-service.json
  e2e/testdata/test-service/go.sum
  e2e/testdata/test-service/main.go
  protobuf/api/execution.pb.go
  protobuf/api/execution.proto
  protobuf/types/struct.pb.go
  protobuf/types/struct.proto
  server/grpc/api/execution.go
  service/service_parameter_test.go
Labels: enhancement

#1491 Filter instances on backend side
  Makefile
  cosmos/client.go
  cosmos/module.go
  e2e/api_test.go
  e2e/instance_test.go
  scripts/build-engine.sh
  scripts/run-e2e.sh
  sdk/instance/backend.go
  sdk/instance/sdk.go
  sdk/service/backend.go
  sdk/service/sdk.go
  server/grpc/api/instance.go
  x/xreflect/xreflect.go
  x/xreflect/xreflect_test.go
Labels: enhancement

#1508 Remove deprecated database files
  database/instance_db.go
  database/instance_db_test.go
  database/ownership_db.go
  database/ownership_db_test.go
  database/service_db.go
  database/service_db_test.go
Labels: refactoring

#1511 Fix bug when Value_NullValue is not taking into account
  service/service_parameter.go
  service/service_parameter_test.go
Labels: release:fix

#1510 Return not found error in backend get functions when resource doesn't exist
  sdk/instance/backend.go
  sdk/runner/backend.go
  sdk/service/backend.go
Labels: release:fix

#1514 Remove service env MESG_TOKEN
  sdk/runner/container.go
Labels: breaking change

#1500 Test/e2e complex service
  e2e/api_test.go
  e2e/complex_service_test.go
  e2e/definition_test.go
  e2e/execution_test.go
  e2e/ownership_test.go
  e2e/runner_test.go
  e2e/service_test.go
  e2e/testdata/test-complex-service/Dockerfile
  e2e/testdata/test-complex-service/go.mod
  e2e/testdata/test-complex-service/go.sum
  e2e/testdata/test-complex-service/main.go
  e2e/testdata/test-complex-service/mesg.yml
  e2e/testdata/test-service.json
  protobuf/types/service.proto
  service/service.pb.go
Labels: tests

#1519 Add data validation to all resource
  .golangci.yml
  account/account.pb.go
  event/event.pb.go
  execution/execution.pb.go
  hash/hash.go
  protobuf/api/event.pb.go
  protobuf/api/event.proto
  protobuf/api/execution.pb.go
  protobuf/api/execution.proto
  protobuf/api/instance.pb.go
  protobuf/api/instance.proto
  protobuf/api/process.pb.go
  protobuf/api/process.proto
  protobuf/api/runner.pb.go
  protobuf/api/runner.proto
  protobuf/api/service.pb.go
  protobuf/api/service.proto
  protobuf/types/account.proto
  protobuf/types/event.proto
  protobuf/types/execution.proto
  sdk/execution/msgs.go
  sdk/runner/msgs.go
  sdk/service/msgs.go
  server/grpc/server.go
  service/validator/validator.go
  x/xvalidator/validator.go
Labels: enhancement

#1490 More verbose error in service backend
  cosmos/errors.go
  cosmos/module.go
  sdk/runner/backend.go
  sdk/runner/msgs.go
  sdk/service/backend.go
Labels: enhancement

#1501 Test/e2e processes
  e2e/api_test.go
  e2e/process_test.go
Labels: tests, waiting dependent pr
