Repository mesg-foundation/engine, pull requests merged in 2019-10, with the labels that each got.

#1380 Feature/config validation
  config/config.go
  config/config_test.go
Labels: enhancement

#1384 Add new service exists api
  cosmos/client.go
  protobuf/api/service.pb.go
  protobuf/api/service.proto
  sdk/ownership/sdk.go
  sdk/service/backend.go
  sdk/service/sdk.go
  sdk/service/type.go
  server/grpc/api/service.go
Labels: enhancement

#1400 Container package refactor
  .circleci/config.yml
  .golangci.yml
  container/build.go
  container/build_integration_test.go
  container/build_test.go
  container/container.go
  container/container_integration_test.go
  container/container_test.go
  container/dockertest/client.go
  container/dockertest/error.go
  container/dockertest/error_test.go
  container/dockertest/requests.go
  container/dockertest/responses.go
  container/dockertest/testing.go
  container/dockertest/testing_test.go
  container/mocks/Container.go
  container/namespace.go
  container/namespace_test.go
  container/network.go
  container/network_integration_test.go
  container/network_test.go
  container/service.go
  container/service_integration_test.go
  container/service_options.go
  container/service_options_test.go
  container/service_test.go
  container/shared_network.go
  container/shared_network_integration_test.go
  container/shared_network_test.go
  container/task.go
  container/task_integration_test.go
  container/task_test.go
  container/test-not-valid/Dockerfile
  container/test/Dockerfile
  container/test/ignoreme
  container/testdata/.dockerignore
  container/testdata/test-image-with-ignore/.dockerignore
  container/testdata/test-image-with-ignore/Dockerfile
  container/testdata/test-image-with-ignore/file.txt
  container/testdata/test-image/Dockerfile
  container/type.go
  container/volume.go
  container/volume_test.go
  container/wait.go
  container/wait_integration_test.go
  container/wait_test.go
  core/main.go
  database/process_db.go
  go.mod
  go.sum
  process/process_test.go
  scripts/build-mocks.sh
  sdk/execution/execution_test.go
  sdk/instance/start.go
  server/grpc/api/execution.go
  utils/docker/mocks/CommonAPIClient.go
Labels: refactoring

#1402 Run scripts from Makefile
  .circleci/config.yml
  .codecov.yml
  .dockerignore
  .gitignore
  Dockerfile
  Dockerfile.tools
  Makefile
  mesg-tools
  scripts/build-engine.sh
  scripts/build-mocks.sh
  scripts/build-proto.sh
  scripts/changelog.sh
  scripts/dev.sh
  scripts/require-mesg-tools.sh
Labels: refactoring

#1414 Remove not used functions from xos package
  x/xos/env.go
  x/xos/env_test.go
  x/xos/file.go
  x/xos/os.go
  x/xos/os_test.go
Labels: refactoring

#1416 Read config from file
  config/config.go
  config/config_test.go
  core/main.go
  go.mod
  go.sum
  scripts/dev.sh
Labels: breaking change

#1431 Dependencies update
  Dockerfile.tools
  go.mod
  go.sum
Labels: dependencies

#1435 Prepare setup for runnign e2e tests
  .circleci/config.yml
  Makefile
  e2e/api_test.go
  scripts/dev.sh
Labels: enhancement

#1439 Setup up account test
  Makefile
  e2e/account_test.go
  e2e/api_test.go
  e2e/testdata/e2e.config.yml
Labels: enhancement

#1440 e2e service test
  e2e/api_test.go
  e2e/service_test.go
  e2e/testdata/test-service.json
  e2e/testdata/test-service/Dockerfile
  e2e/testdata/test-service/go.mod
  e2e/testdata/test-service/go.sum
  e2e/testdata/test-service/main.go
  e2e/testdata/test-service/mesg.yml
Labels: enhancement

#1441 e2e ownership test
  e2e/api_test.go
  e2e/ownership_test.go
Labels: enhancement

#1442 e2e instance test
  e2e/api_test.go
  e2e/instance_test.go
Labels: enhancement

#1443 e2e event test
  e2e/api_test.go
  e2e/event_test.go
Labels: enhancement

#1444 e2e execution test
  e2e/api_test.go
  e2e/execution_test.go
  e2e/instance_test.go
  e2e/testdata/test-service.json
  e2e/testdata/test-service/main.go
  e2e/testdata/test-service/mesg.yml
Labels: enhancement

#1448 Pass MESG_INSTANCE_HASH to service
  e2e/testdata/test-service/main.go
  sdk/instance/start.go
Labels: bug, enhancement

#1449 Add config.log.format validation
  config/config.go
Labels: bug, enhancement

#1452 Add EnvHash to instance and calculate the hash based on it
  cosmos/client.go
  e2e/instance_test.go
  e2e/testdata/test-service.json
  e2e/testdata/test-service/mesg.yml
  instance/instance.pb.go
  protobuf/types/instance.proto
  sdk/instance/instance.go
  x/xos/env.go
  x/xos/env_test.go
  x/xvalidator/validator.go
Labels: enhancement

#1450 Add more explicit error on service create
  sdk/service/sdk.go
Labels: enhancement
