Repository mesg-foundation/engine, pull requests merged in 2019-07, with the labels that each got.

#1158 Shared network on multiple engine
  dev
Labels: low priority

#1166 Update mesg-js of service marketplace and compile it
  systemservices/marketplace/.mesgignore
  systemservices/marketplace/compiled.json
  systemservices/marketplace/package-lock.json
  systemservices/marketplace/package.json
Labels: high priority

#1167 Add .mesgignore in ethwallet and compile it
  systemservices/ethwallet/.mesgignore
  systemservices/ethwallet/compiled.json
Labels: high priority

#1170 update db versions
  config/config.go
Labels: high priority

#1173 Update docker labels
  sdk/instance/start.go
Labels: breaking change, enhancement

#1174 Do not use config inside instance sdk
  core/main.go
  sdk/execution/execution_test.go
  sdk/instance/instance.go
  sdk/instance/start.go
  sdk/sdk.go
  server/grpc/api/execution_test.go
  server/grpc/core/test_test.go
Labels: refactoring

#1172 Workflow engine foundations
  core/main.go
  workflow/type.go
  workflow/workflow.go
Labels: enhancement

#1175 Attach event to execution
  sdk/execution/execution.go
  sdk/execution/execution_test.go
  server/grpc/api/execution.go
  workflow/workflow.go
Labels: enhancement, help wanted

#1184 Log errors from the workflow as warning
  core/main.go
Labels: enhancement

#1181 Workflow filters
  workflow/type.go
  workflow/type_test.go
  workflow/workflow.go
Labels: enhancement

#1182 Add support of results for workflow triggers
  sdk/execution/execution.go
  sdk/execution/execution_test.go
  server/grpc/api/execution.go
  workflow/type.go
  workflow/type_test.go
  workflow/workflow.go
Labels: breaking change, enhancement

#1185 Reorganization of service package
  sdk/service/service.go
  service/dependency.go
  service/dependency_test.go
  service/event.go
  service/event_test.go
  service/parameter.go
  service/service.go
  service/service_test.go
  service/task.go
  service/type.go
  service/validator/validator.go
Labels: refactoring

#1186 Fix hash key for dependency
  service/type.go
Labels: bug

#1188 Workflow service
  core/main.go
  protobuf/api/service.pb.go
  protobuf/api/service.proto
  protobuf/types/service.pb.go
  protobuf/types/service.proto
  server/grpc/api/mapping.go
  server/grpc/api/service.go
  service/type.go
  service/workflow.go
  service/workflow_test.go
  workflow/type.go
  workflow/type_test.go
  workflow/workflow.go
Labels: enhancement

#1190 Add key to workflow
  protobuf/types/service.pb.go
  protobuf/types/service.proto
  server/grpc/api/mapping.go
  service/type.go
Labels: enhancement

#1191 Put execution to failed state on validation error
  sdk/execution/execution.go
Labels: enhancement

#1192 Replace json format with protobuf Struct
  Dockerfile.tools
  protobuf/api/event.pb.go
  protobuf/api/event.proto
  protobuf/api/execution.pb.go
  protobuf/api/execution.proto
  protobuf/convert/pbstruct.go
  protobuf/types/event.pb.go
  protobuf/types/event.proto
  protobuf/types/execution.pb.go
  protobuf/types/execution.proto
  sdk/execution/execution.go
  server/grpc/api/event.go
  server/grpc/api/execution.go
  systemservices/ethwallet/client/encoding.go
  systemservices/ethwallet/client/task_runner.go
  systemservices/ethwallet/compiled.json
  systemservices/ethwallet/ethwallet/create.go
  systemservices/ethwallet/ethwallet/delete.go
  systemservices/ethwallet/ethwallet/export.go
  systemservices/ethwallet/ethwallet/import.go
  systemservices/ethwallet/ethwallet/importFromPrivateKey.go
  systemservices/ethwallet/ethwallet/list.go
  systemservices/ethwallet/ethwallet/sign.go
  systemservices/ethwallet/go.mod
  systemservices/ethwallet/go.sum
Labels: breaking change, enhancement

#1199 Update marketplace service
  systemservices/marketplace/compiled.json
  systemservices/marketplace/package-lock.json
  systemservices/marketplace/package.json
Labels: bug

#1200 Update changelog for v0.12.1
  CHANGELOG.md
Labels: documentation
