Repository mesg-foundation/engine, pull requests merged in 2020-02, with the labels that each got.

#1632 Add target to run engine in dev mode with monitoring
  Makefile
  scripts/datasource.yml
  scripts/dev.sh
  scripts/prometheus.yml
Labels: enhancement

#1645 Improve LCD server
  config/config.go
  core/main.go
Labels: enhancement

#1651 Use template to move ownership cosmos module to x/ dir
  .golangci.yml
  app/app.go
  core/main.go
  cosmos/client.go
  e2e/testdata/test-complex-service/main.go
  ext/xerrors/errors.go
  ext/xerrors/errors_test.go
  ext/xnet/dnsclient.go
  ext/xnet/ip_test.go
  ext/xnet/ipsock.go
  ext/xos/env.go
  ext/xos/env_test.go
  ext/xrand/seed.go
  ext/xreflect/xreflect.go
  ext/xreflect/xreflect_test.go
  ext/xsignal/signal.go
  ext/xsignal/signal_test.go
  ext/xstrings/strings.go
  ext/xstrings/strings_test.go
  ext/xvalidator/validator.go
  protobuf/api/execution.go
  sdk/execution/msgs.go
  sdk/ownership/keeper.go
  sdk/ownership/module.go
  sdk/ownership/sdk.go
  sdk/process/keeper.go
  sdk/process/msgs.go
  sdk/runner/container.go
  sdk/runner/msgs.go
  sdk/runner/sdk.go
  sdk/sdk.go
  sdk/service/keeper.go
  sdk/service/msgs.go
  server/grpc/api/ownership.go
  server/grpc/server.go
  server/grpc/server_test.go
  service/service_parameter.go
  service/validator/validator.go
  x/.gitkeep
  x/ownership/abci.go
  x/ownership/alias.go
  x/ownership/client/cli/query.go
  x/ownership/client/cli/tx.go
  x/ownership/client/rest/query.go
  x/ownership/client/rest/rest.go
  x/ownership/client/rest/tx.go
  x/ownership/genesis.go
  x/ownership/handler.go
  x/ownership/internal/keeper/keeper.go
  x/ownership/internal/keeper/querier.go
  x/ownership/internal/types/codec.go
  x/ownership/internal/types/expected_keepers.go
  x/ownership/internal/types/genesis.go
  x/ownership/internal/types/key.go
  x/ownership/internal/types/params.go
  x/ownership/internal/types/querier.go
  x/ownership/module.go
Labels: refactoring, release:change

#1654 add e2e lcd test for ownerships
  e2e/api_test.go
  e2e/process_test.go
  e2e/service_test.go
Labels: release:add

#1657 Use template to move runner cosmos module to x/ dir
  app/app.go
  sdk/execution/keeper.go
  sdk/runner/codec.go
  sdk/runner/keeper.go
  sdk/runner/module.go
  sdk/runner/msgs.go
  sdk/runner/sdk.go
  x/runner/abci.go
  x/runner/alias.go
  x/runner/client/cli/query.go
  x/runner/client/cli/tx.go
  x/runner/client/rest/query.go
  x/runner/client/rest/rest.go
  x/runner/client/rest/tx.go
  x/runner/genesis.go
  x/runner/handler.go
  x/runner/internal/keeper/keeper.go
  x/runner/internal/keeper/querier.go
  x/runner/internal/types/codec.go
  x/runner/internal/types/events.go
  x/runner/internal/types/expected_keepers.go
  x/runner/internal/types/genesis.go
  x/runner/internal/types/key.go
  x/runner/internal/types/msg.go
  x/runner/internal/types/params.go
  x/runner/internal/types/querier.go
  x/runner/module.go
Labels: refactoring

#1658 Use template to move process cosmos module to x/ dir
  app/app.go
  process/codec.go
  sdk/execution/keeper.go
  sdk/process/codec.go
  sdk/process/keeper.go
  sdk/process/module.go
  sdk/process/msgs.go
  sdk/process/sdk.go
  x/process/abci.go
  x/process/alias.go
  x/process/client/cli/query.go
  x/process/client/cli/tx.go
  x/process/client/rest/query.go
  x/process/client/rest/rest.go
  x/process/client/rest/tx.go
  x/process/genesis.go
  x/process/handler.go
  x/process/internal/keeper/keeper.go
  x/process/internal/keeper/querier.go
  x/process/internal/types/codec.go
  x/process/internal/types/events.go
  x/process/internal/types/expected_keepers.go
  x/process/internal/types/genesis.go
  x/process/internal/types/key.go
  x/process/internal/types/msg.go
  x/process/internal/types/params.go
  x/process/internal/types/querier.go
  x/process/module.go
Labels: refactoring

#1661 Use template to move service cosmos module to x/ dir
  app/app.go
  sdk/execution/keeper.go
  sdk/service/codec.go
  sdk/service/keeper.go
  sdk/service/module.go
  sdk/service/msgs.go
  sdk/service/sdk.go
  x/service/abci.go
  x/service/alias.go
  x/service/client/cli/query.go
  x/service/client/cli/tx.go
  x/service/client/rest/query.go
  x/service/client/rest/rest.go
  x/service/client/rest/tx.go
  x/service/genesis.go
  x/service/handler.go
  x/service/internal/keeper/keeper.go
  x/service/internal/keeper/querier.go
  x/service/internal/types/codec.go
  x/service/internal/types/events.go
  x/service/internal/types/expected_keepers.go
  x/service/internal/types/genesis.go
  x/service/internal/types/key.go
  x/service/internal/types/msg.go
  x/service/internal/types/params.go
  x/service/internal/types/querier.go
  x/service/module.go
Labels: refactoring, release:add

#1662 Refactor/cosmos execution module
  app/app.go
  codec/codec.go
  core/main.go
  cosmos/client.go
  cosmos/genesis.go
  cosmos/genesis_test.go
  cosmos/module.go
  go.mod
  go.sum
  protobuf/api/codec.go
  protobuf/types/codec.go
  protobuf/types/struct_test.go
  sdk/execution/codec.go
  sdk/execution/keeper.go
  sdk/execution/module.go
  sdk/execution/msgs.go
  sdk/execution/sdk.go
  x/execution/abci.go
  x/execution/alias.go
  x/execution/client/cli/query.go
  x/execution/client/cli/tx.go
  x/execution/client/rest/query.go
  x/execution/client/rest/rest.go
  x/execution/client/rest/tx.go
  x/execution/genesis.go
  x/execution/handler.go
  x/execution/internal/keeper/keeper.go
  x/execution/internal/keeper/metrics.go
  x/execution/internal/keeper/querier.go
  x/execution/internal/types/codec.go
  x/execution/internal/types/events.go
  x/execution/internal/types/expected_keepers.go
  x/execution/internal/types/genesis.go
  x/execution/internal/types/key.go
  x/execution/internal/types/msg.go
  x/execution/internal/types/params.go
  x/execution/internal/types/querier.go
  x/execution/module.go
  x/process/internal/keeper/keeper.go
  x/runner/internal/keeper/keeper.go
  x/service/internal/keeper/keeper.go
Labels: refactoring, release:add

#1663 add a bunch of e2e test using the lcd
  e2e/api_test.go
  e2e/execution_test.go
  e2e/instance_test.go
  e2e/process_test.go
  e2e/runner_test.go
  e2e/service_test.go
Labels: release:add

#1650 Refactor of cosmos modules
  Dockerfile.tools
  Makefile
  core/main.go
  cosmos/client.go
  cosmos/errors/errors.go
  cosmos/module_client.go
  event/event.go
  event/event_listener.go
  event/event_listener_test.go
  event/publisher/publisher.go
  go.mod
  go.sum
  internal/tools/tools.go
  orchestrator/mocks/EventSDK.go
  orchestrator/mocks/ExecutionSDK.go
  orchestrator/mocks/ProcessSDK.go
  orchestrator/mocks/RunnerSDK.go
  orchestrator/orchestrator.go
  orchestrator/orchestrator_test.go
  orchestrator/type.go
  runner/builder/builder.go
  runner/builder/container.go
  scripts/build-mocks.sh
  sdk/event/event.go
  sdk/execution/sdk.go
  sdk/process/sdk.go
  sdk/runner/sdk.go
  sdk/sdk.go
  sdk/service/sdk.go
  server/grpc/api/event.go
  server/grpc/api/execution.go
  server/grpc/api/instance.go
  server/grpc/api/ownership.go
  server/grpc/api/process.go
  server/grpc/api/runner.go
  server/grpc/api/service.go
  server/grpc/server.go
  x/execution/internal/keeper/querier.go
  x/execution/internal/types/msg.go
  x/instance/internal/keeper/querier.go
  x/process/internal/keeper/querier.go
  x/runner/internal/keeper/querier.go
  x/runner/internal/types/msg.go
  x/service/internal/keeper/querier.go
Labels: refactoring, release:change

#1669 Use disable-all instead of enable-all in golangci config
  .golangci.yml
Labels: refactoring, release:change

#1670 Implement first iteration of the executions ecomomy
  app/app.go
  e2e/api_test.go
  e2e/execution_test.go
  execution/execution.go
  execution/execution.pb.go
  execution/execution_test.go
  ext/xvalidator/validator.go
  protobuf/api/execution.pb.go
  protobuf/api/execution.proto
  protobuf/types/execution.proto
  x/execution/internal/keeper/keeper.go
  x/execution/internal/types/expected_keepers.go
  x/execution/internal/types/msg.go
Labels: enhancement, release:add

#1680 add block height to execution
  execution/execution.pb.go
  protobuf/types/execution.proto
  x/execution/internal/keeper/keeper.go
Labels: enhancement

#1682 Fix Tendermint graceful stop
  app/app.go
  cmd/mesg-daemon/main.go
  core/main.go
  orchestrator/orchestrator.go
  orchestrator/type.go
Labels: release:fix

#1689 Add pagination system on http handler of executions/list
  execution/sort.go
  x/execution/client/rest/query.go
Labels: release:add

#1683 Make sure to call end block for each modules
  x/execution/module.go
  x/instance/module.go
  x/ownership/module.go
  x/process/module.go
  x/runner/module.go
  x/service/module.go
Labels: bug
