Repository mesg-foundation/engine, pull requests merged in 2020-03, with the labels that each got.

#1691 Add min price for execution
  app/app.go
  config/config.go
  core/main.go
  e2e/execution_test.go
  orchestrator/orchestrator.go
  orchestrator/type.go
  server/grpc/api/execution.go
  server/grpc/server.go
  server/grpc/server_test.go
  x/execution/genesis.go
  x/execution/internal/keeper/keeper.go
  x/execution/internal/keeper/params.go
  x/execution/internal/types/genesis.go
  x/execution/internal/types/params.go
  x/execution/module.go
Labels: enhancement, release:add

#1692 Custom hash serializer
  cosmos/module_client.go
  e2e/instance_test.go
  event/serialize.go
  event/serialize_test.go
  execution/serialize.go
  execution/serialize_test.go
  go.mod
  hash/hash.go
  hash/hash_test.go
  hash/hashserializer/hashserializer.go
  hash/hashserializer/hashserializer_test.go
  hash/structhash/structhash.go
  hash/structhash/structhash_test.go
  instance/serialize.go
  instance/serialize_test.go
  ownership/serialize.go
  ownership/serialize_test.go
  process/serialize.go
  process/serialize_test.go
  protobuf/types/serialize.go
  protobuf/types/serialize_test.go
  protobuf/types/service.proto
  protobuf/types/struct_test.go
  runner/builder/builder.go
  runner/builder/container.go
  runner/serialize.go
  runner/serialize_test.go
  service/serialize.go
  service/serialize_test.go
  service/service.pb.go
Labels: release:change

#1688 Handle withdraw from resources
  app/app.go
  core/main.go
  cosmos/client.go
  e2e/api_test.go
  e2e/execution_test.go
  e2e/process_test.go
  e2e/runner_test.go
  ownership/ownership.pb.go
  protobuf/types/ownership.proto
  x/execution/handler.go
  x/ownership/alias.go
  x/ownership/client/cli/tx.go
  x/ownership/client/rest/tx.go
  x/ownership/handler.go
  x/ownership/internal/keeper/keeper.go
  x/ownership/internal/types/codec.go
  x/ownership/internal/types/events.go
  x/ownership/internal/types/expected_keepers.go
  x/ownership/internal/types/msg.go
  x/runner/internal/keeper/keeper.go
  x/runner/internal/types/expected_keepers.go
Labels: enhancement, release:add

#1719 Add transaction's log to returned error
  cosmos/client.go
Labels: release:add

#1694 add build multi-platform cmds script to CI
  .circleci/config.yml
  Makefile
  go.mod
  go.sum
  internal/tools/tools.go
  scripts/publish-cmds.sh
Labels: release:add

#1699 Get coins from execution's process if attached
  app/app.go
  config/config.go
  e2e/api_test.go
  e2e/execution_test.go
  e2e/orchestrator_balance_withdraw_test.go
  e2e/orchestrator_test.go
  e2e/process_test.go
  e2e/runner_test.go
  x/execution/internal/keeper/keeper.go
  x/process/internal/keeper/keeper.go
  x/process/internal/types/expected_keepers.go
Labels: enhancement, on-hold, release:add

#1717 Revert "Custom hash serializer"
  cosmos/module_client.go
  e2e/instance_test.go
  event/serialize.go
  event/serialize_test.go
  execution/serialize.go
  execution/serialize_test.go
  go.mod
  hash/hash.go
  hash/hash_test.go
  hash/hashserializer/hashserializer.go
  hash/hashserializer/hashserializer_test.go
  hash/structhash/structhash.go
  hash/structhash/structhash_test.go
  instance/serialize.go
  instance/serialize_test.go
  ownership/serialize.go
  ownership/serialize_test.go
  process/serialize.go
  process/serialize_test.go
  protobuf/types/serialize.go
  protobuf/types/serialize_test.go
  protobuf/types/service.proto
  protobuf/types/struct_test.go
  runner/builder/builder.go
  runner/builder/container.go
  runner/serialize.go
  runner/serialize_test.go
  service/serialize.go
  service/serialize_test.go
  service/service.pb.go
Labels: release:change

#1723 Add address to process
  e2e/process_test.go
  process/process.pb.go
  protobuf/types/process.proto
  x/process/internal/keeper/keeper.go
Labels: enhancement, release:add

#1705 Execution emitter consensus
  cosmos/errors/errors.go
  e2e/execution_test.go
  execution/execution.go
  execution/execution.pb.go
  execution/execution_test.go
  process/graph.go
  protobuf/api/execution_test.go
  protobuf/types/execution.proto
  x/execution/handler.go
  x/execution/internal/keeper/keeper.go
  x/execution/internal/types/events.go
  x/execution/internal/types/expected_keepers.go
Labels: release:add

#1728 Add address field to service, runner, execution, and execution
  core/main.go
  cosmos/module_client.go
  e2e/execution_test.go
  e2e/orchestrator_balance_withdraw_test.go
  e2e/process_test.go
  e2e/runner_test.go
  e2e/service_test.go
  execution/execution.go
  execution/execution.pb.go
  ownership/ownership.pb.go
  process/process.go
  process/process.pb.go
  protobuf/api/runner.pb.go
  protobuf/api/runner.proto
  protobuf/types/execution.proto
  protobuf/types/ownership.proto
  protobuf/types/process.proto
  protobuf/types/runner.proto
  protobuf/types/service.proto
  runner/builder/builder.go
  runner/runner.go
  runner/runner.pb.go
  server/grpc/api/runner.go
  service/service.pb.go
  x/execution/internal/keeper/keeper.go
  x/ownership/internal/keeper/keeper.go
  x/process/internal/keeper/keeper.go
  x/process/internal/types/expected_keepers.go
  x/process/internal/types/msg.go
  x/runner/internal/keeper/keeper.go
  x/runner/internal/types/expected_keepers.go
  x/runner/internal/types/msg.go
  x/service/internal/keeper/keeper.go
  x/service/internal/types/expected_keepers.go
Labels: release:add

#1729 Wrap errors of modules' keeper, querier and msg to sent them to clients
  cosmos/errors/errors.go
  go.sum
  x/execution/client/rest/query.go
  x/execution/handler.go
  x/execution/internal/keeper/keeper.go
  x/execution/internal/keeper/querier.go
  x/execution/internal/types/msg.go
  x/instance/client/rest/query.go
  x/instance/internal/keeper/keeper.go
  x/instance/internal/keeper/querier.go
  x/ownership/client/rest/query.go
  x/ownership/internal/keeper/keeper.go
  x/ownership/internal/types/msg.go
  x/process/client/rest/query.go
  x/process/handler.go
  x/process/internal/keeper/keeper.go
  x/process/internal/keeper/querier.go
  x/process/internal/types/msg.go
  x/runner/client/rest/query.go
  x/runner/handler.go
  x/runner/internal/keeper/keeper.go
  x/runner/internal/keeper/querier.go
  x/runner/internal/types/msg.go
  x/service/client/rest/query.go
  x/service/handler.go
  x/service/internal/keeper/keeper.go
  x/service/internal/keeper/querier.go
  x/service/internal/types/msg.go
Labels: release:add

#1737 Add support for any type of data to filter
  e2e/orchestrator_filter_test.go
  process/filter.go
  process/filter_test.go
  process/process.pb.go
  protobuf/types/process.proto
  x/process/internal/types/codec.go
Labels: breaking change, release:add

#1738 Add more predicates to process filter
  e2e/orchestrator_filter_test.go
  e2e/orchestrator_test.go
  process/filter.go
  process/filter_test.go
  process/process.go
  process/process.pb.go
  process/process_test.go
  protobuf/types/process.proto
Labels: release:add

#1742 Simpler messages using protobuf definiton
  cosmos/module_client.go
  e2e/definition_test.go
  e2e/execution_test.go
  e2e/service_test.go
  ext/xerrors/errors.go
  ext/xerrors/errors_test.go
  ext/xvalidator/validator.go
  process/process.go
  process/process_test.go
  protobuf/api/service.pb.go
  protobuf/api/service.proto
  protobuf/types/service.proto
  scripts/build-proto.sh
  server/grpc/server.go
  service/service.pb.go
  service/validate.go
  x/execution/alias.go
  x/execution/handler.go
  x/execution/internal/keeper/keeper.go
  x/execution/internal/types/codec.go
  x/execution/internal/types/msg.go
  x/execution/internal/types/msg.pb.go
  x/execution/internal/types/msg.proto
  x/ownership/alias.go
  x/ownership/client/cli/tx.go
  x/ownership/client/rest/tx.go
  x/ownership/handler.go
  x/ownership/internal/keeper/keeper.go
  x/ownership/internal/types/codec.go
  x/ownership/internal/types/events.go
  x/ownership/internal/types/msg.go
  x/ownership/internal/types/msg.pb.go
  x/ownership/internal/types/msg.proto
  x/process/alias.go
  x/process/handler.go
  x/process/internal/keeper/keeper.go
  x/process/internal/types/codec.go
  x/process/internal/types/msg.go
  x/process/internal/types/msg.pb.go
  x/process/internal/types/msg.proto
  x/runner/alias.go
  x/runner/handler.go
  x/runner/internal/keeper/keeper.go
  x/runner/internal/types/codec.go
  x/runner/internal/types/msg.go
  x/runner/internal/types/msg.pb.go
  x/runner/internal/types/msg.proto
  x/service/alias.go
  x/service/client/rest/query.go
  x/service/handler.go
  x/service/internal/keeper/keeper.go
  x/service/internal/types/codec.go
  x/service/internal/types/msg.go
  x/service/internal/types/msg.pb.go
  x/service/internal/types/msg.proto
Labels: breaking change

#1752 Update to cosmos-sdk v0.38.2 and tendermint v0.33.2
  go.mod
  go.sum
Labels: dependencies

#1749 Add more validation on resources
  event/event.pb.go
  execution/execution.go
  execution/execution.pb.go
  execution/execution_test.go
  instance/instance.go
  instance/instance.pb.go
  ownership/ownership.go
  ownership/ownership.pb.go
  process/process.go
  process/process.pb.go
  process/process_test.go
  protobuf/types/event.proto
  protobuf/types/execution.proto
  protobuf/types/instance.proto
  protobuf/types/ownership.proto
  protobuf/types/process.proto
  protobuf/types/runner.proto
  runner/builder/builder.go
  runner/runner.go
  runner/runner.pb.go
  service/service.go
  x/execution/internal/keeper/keeper.go
  x/instance/internal/keeper/keeper.go
  x/ownership/internal/keeper/keeper.go
  x/process/client/rest/query.go
  x/process/internal/keeper/keeper.go
  x/process/internal/types/msg.go
  x/runner/client/rest/query.go
  x/runner/internal/keeper/keeper.go
  x/service/client/rest/query.go
  x/service/internal/keeper/keeper.go
Labels: release:add

#1754 Update service hash endpoint
  e2e/definition_test.go
  e2e/service_test.go
  x/service/client/rest/query.go
Labels: enhancement

#1755 Update lcd process hash endpoint to use a dedicated request structure
  e2e/process_test.go
  e2e/service_test.go
  x/process/client/rest/query.go
Labels: release:change

#1751 Replace gRPC by LCD as much as possible from e2e tests
  config/config.go
  cosmos/client.go
  e2e/api_test.go
  e2e/complex_service_test.go
  e2e/definition_test.go
  e2e/execution_test.go
  e2e/instance_test.go
  e2e/lcd_test.go
  e2e/orchestrator_balance_withdraw_test.go
  e2e/orchestrator_event_task_test.go
  e2e/orchestrator_filter_path_nested_test.go
  e2e/orchestrator_filter_test.go
  e2e/orchestrator_map_const_test.go
  e2e/orchestrator_nested_data_test.go
  e2e/orchestrator_nested_map_test.go
  e2e/orchestrator_ref_grand_parent_task_test.go
  e2e/orchestrator_ref_path_nested_test.go
  e2e/orchestrator_result_task_test.go
  e2e/orchestrator_test.go
  e2e/process_test.go
  e2e/runner_test.go
  e2e/service_test.go
  e2e/testdata/test-complex-service/main.go
Labels: release:change

#1759 add 2 more linters and remove useless exclusion
  .golangci.yml
Labels: release:add

#1756 Change gogoproto's customtype to casttype
  event/event.pb.go
  execution/execution.pb.go
  hash/hash.go
  hash/hash_test.go
  instance/instance.pb.go
  ownership/ownership.pb.go
  process/process.pb.go
  protobuf/api/event.pb.go
  protobuf/api/event.proto
  protobuf/api/execution.pb.go
  protobuf/api/execution.proto
  protobuf/api/instance.pb.go
  protobuf/api/instance.proto
  protobuf/api/process.pb.go
  protobuf/api/process.proto
  protobuf/api/runner.pb.go
  protobuf/api/runner.proto
  protobuf/api/service.pb.go
  protobuf/api/service.proto
  protobuf/types/event.proto
  protobuf/types/execution.proto
  protobuf/types/instance.proto
  protobuf/types/ownership.proto
  protobuf/types/process.proto
  protobuf/types/runner.proto
  protobuf/types/service.proto
  runner/runner.pb.go
  service/service.pb.go
  x/execution/internal/types/msg.pb.go
  x/execution/internal/types/msg.proto
  x/ownership/internal/types/msg.pb.go
  x/ownership/internal/types/msg.proto
  x/process/internal/types/msg.pb.go
  x/process/internal/types/msg.proto
  x/runner/internal/types/msg.pb.go
  x/runner/internal/types/msg.proto
Labels: release:change

#1757 Replace runner gRPC by LCD in e2e tests
  e2e/api_test.go
  e2e/complex_service_test.go
  e2e/definition_test.go
  e2e/runner_test.go
  e2e/service_test.go
  runner/builder/builder.go
  runner/builder/container.go
Labels: release:change

#1758 Introduce a simple LCD client
  core/main.go
  cosmos/lcd.go
  cosmos/module_client.go
  cosmos/rpc.go
  e2e/api_test.go
  e2e/complex_service_test.go
  e2e/execution_test.go
  e2e/instance_test.go
  e2e/lcd_test.go
  e2e/orchestrator_balance_withdraw_test.go
  e2e/orchestrator_event_task_test.go
  e2e/orchestrator_filter_path_nested_test.go
  e2e/orchestrator_filter_test.go
  e2e/orchestrator_map_const_test.go
  e2e/orchestrator_nested_data_test.go
  e2e/orchestrator_nested_map_test.go
  e2e/orchestrator_ref_grand_parent_task_test.go
  e2e/orchestrator_ref_path_nested_test.go
  e2e/orchestrator_result_task_test.go
  e2e/process_test.go
  e2e/runner_test.go
  e2e/service_test.go
Labels: release:add

#1761 Remove module suffix from lot of places
  cosmos/module_client.go
  x/execution/alias.go
  x/execution/client/cli/query.go
  x/execution/client/rest/query.go
  x/execution/internal/keeper/keeper.go
  x/execution/internal/keeper/querier.go
  x/execution/internal/types/querier.go
  x/instance/alias.go
  x/instance/client/cli/query.go
  x/instance/client/rest/query.go
  x/instance/internal/keeper/querier.go
  x/instance/internal/types/querier.go
  x/ownership/alias.go
  x/ownership/client/cli/query.go
  x/ownership/client/rest/query.go
  x/ownership/internal/keeper/keeper.go
  x/ownership/internal/keeper/querier.go
  x/ownership/internal/types/querier.go
  x/process/alias.go
  x/process/client/cli/query.go
  x/process/client/cli/tx.go
  x/process/client/rest/query.go
  x/process/internal/keeper/querier.go
  x/process/internal/types/querier.go
  x/runner/alias.go
  x/runner/client/cli/query.go
  x/runner/client/cli/tx.go
  x/runner/client/rest/query.go
  x/runner/internal/keeper/querier.go
  x/runner/internal/types/querier.go
  x/service/alias.go
  x/service/client/cli/query.go
  x/service/client/rest/query.go
  x/service/internal/keeper/querier.go
  x/service/internal/types/querier.go
Labels: release:change
