Repository mesg-foundation/engine, pull requests merged in 2020-01, with the labels that each got.

#1572 Customize cosmos config for mesg engine
  core/main.go
  cosmos/config.go
Labels: enhancement

#1588 Fix supply module init
  sdk/backend.go
Labels: release:fix

#1580 Engine execution stats
  go.mod
  go.sum
  scripts/dev.sh
  sdk/execution/backend.go
  sdk/execution/metrics.go
  sdk/execution/sdk.go
  server/grpc/server.go
Labels: proposal

#1599 Move AccNumber and AccIndex to the config
  config/config.go
  config/config_test.go
  core/main.go
  cosmos/genesis_test.go
  cosmos/keybase.go
  cosmos/keybase_test.go
Labels: waiting dependent pr

#1598 Fix account number used for signing tx
  .dockerignore
  config/config.go
  config/config_test.go
  core/main.go
  cosmos/client.go
  cosmos/genesis.go
  cosmos/genesis_test.go
  cosmos/keybase.go
  cosmos/keybase_test.go
  cosmos/txbuilder.go
Labels: release:fix, waiting dependent pr

#1602 Change the mesg coin type to the registered one (470)
  cosmos/config.go
Labels: release:change
