Repository mesg-foundation/engine, pull requests merged in 2020-05, with the labels that each got.

#1760 Set grace period to 1m in dev script
  scripts/dev.sh
Labels: release:fix

#1802 Rename in cosmos lcd and rpc clients minGasPrices by simply gasPrices
  cosmos/lcd.go
  cosmos/rpc.go
Labels: release:change

#1803 update readme
  README.md
Labels: release:change

#1798 Add tx commands for service, process, execution and runner modules
  x/execution/client/cli/tx.go
  x/instance/client/cli/tx.go
  x/ownership/client/cli/tx.go
  x/process/client/cli/tx.go
  x/runner/client/cli/tx.go
  x/service/client/cli/tx.go
Labels: release:add

#1801 Add orchestrator command to CLI
  app/app.go
  cmd/mesg-cli/main.go
  cmd/mesg-cli/orchestrator.go
  cmd/mesg-daemon/main.go
  cosmos/keybase.go
  ext/xstrings/strings.go
  orchestrator/orchestrator.go
Labels: release:add

#1809 fix runner e2e that block the tests on error
  e2e/runner_test.go
Labels: release:fix

#1808 Add cli dockerfile
  Dockerfile.cli
  Dockerfile.tools
  Makefile
Labels: release:add

#1811 Revert golang/protobuf to v1.3.5 and prometheus/client_golang to v1.5.1
  go.mod
  go.sum
Labels: dependencies

#1806 Create pre-configured dev docker image
  .circleci/config.yml
  .dockerignore
  Dockerfile.cli.dev
  Makefile
  dev-chain/README.md
  dev-chain/cli/config/config.toml
  dev-chain/validator/config/app.toml
  dev-chain/validator/config/config.toml
  dev-chain/validator/config/genesis.json
  dev-chain/validator/config/node_key.json
  dev-chain/validator/config/priv_validator_key.json
  dev-chain/validator/data/priv_validator_state.json
  e2e/api_test.go
  e2e/testdata/e2e.config.yml
  scripts/dev-cli.sh
  scripts/run-e2e.sh
Labels: release:add

#1810 Switch to CLI based Engine
  .circleci/config.yml
  .dockerignore
  Dockerfile
  Dockerfile.cli
  Dockerfile.cli.dev
  Dockerfile.dev
  Makefile
  config/config.go
  config/config_test.go
  core/main.go
  cosmos/config.go
  cosmos/genesis.go
  cosmos/genesis_test.go
  cosmos/keybase.go
  cosmos/node.go
  e2e/api_test.go
  e2e/orchestrator_balance_withdraw_test.go
  go.mod
  logger/init.go
  logger/tendermint.go
  scripts/build-cli.sh
  scripts/build-engine.sh
  scripts/dev-starter.sh
  scripts/dev.sh
  scripts/publish-cli.sh
  scripts/publish-cmds.sh
  scripts/run-e2e.sh
  version/version.go
Labels: breaking change

#1817 Use docker container in e2e tests
  container/container.go
  e2e/api_test.go
  go.mod
  scripts/run-e2e.sh
Labels: release:change

#1812 Add orchestrator logs and publish them on a new gRPC stream
  cmd/mesg-cli/orchestrator.go
  go.mod
  orchestrator/orchestrator.go
  orchestrator/type.go
  process/node.go
  server/grpc/logger.go
  server/grpc/server.go
Labels: release:add

#1827 update dev script to use docker container instead of docker service
  Makefile
  scripts/dev.sh
Labels: release:change

#1825 Add filter on execution list
  e2e/api_test.go
  x/execution/client/rest/query.go
  x/execution/internal/keeper/keeper.go
  x/execution/internal/keeper/querier.go
  x/execution/internal/types/querier.go
Labels: enhancement, release:add

#1826 Add pagination meta data in the header
  x/execution/client/rest/query.go
Labels: enhancement

#1828 Improve CLI commands
  x/execution/alias.go
  x/execution/client/cli/query.go
  x/execution/client/cli/tx.go
  x/execution/client/rest/query.go
  x/execution/internal/keeper/querier.go
  x/execution/internal/types/querier.go
  x/instance/client/cli/query.go
  x/ownership/alias.go
  x/ownership/client/cli/query.go
  x/ownership/client/cli/tx.go
  x/ownership/client/rest/query.go
  x/ownership/internal/types/params.go
  x/process/alias.go
  x/process/client/cli/query.go
  x/process/client/cli/tx.go
  x/process/client/rest/query.go
  x/process/internal/types/params.go
  x/runner/alias.go
  x/runner/client/cli/query.go
  x/runner/client/cli/tx.go
  x/runner/client/rest/query.go
  x/runner/internal/types/params.go
  x/service/alias.go
  x/service/client/cli/query.go
  x/service/client/cli/tx.go
  x/service/internal/types/params.go
Labels: release:change

#1830 Revert "Fix 2 issues with instance"
  app/app.go
  instance/instance.pb.go
  protobuf/types/instance.proto
  x/instance/internal/keeper/keeper.go
  x/instance/internal/types/expected_keepers.go
Labels: breaking change

#1831 Switch to json logger in orchestrator and daemon
  cmd/mesg-cli/main.go
  cmd/mesg-cli/orchestrator.go
  cmd/mesg-cli/serve.go
  cmd/mesg-daemon/main.go
Labels: release:change

#1843 Display body in lcd client on error
  cosmos/lcd.go
Labels: release:fix

#1845 Set default flag gasPrice of the orchestrator to null
  cmd/mesg-cli/orchestrator.go
Labels: release:change

#1846 Fix command execution list because of not set filter
  x/execution/client/cli/query.go
Labels: release:fix

#1851 Remove swarm init from ci
  .circleci/config.yml
Labels: release:change

#1848 Implement import and export functions in modules
  x/execution/genesis.go
  x/execution/internal/keeper/keeper.go
  x/execution/internal/types/genesis.go
  x/instance/genesis.go
  x/instance/internal/keeper/keeper.go
  x/instance/internal/types/genesis.go
  x/ownership/genesis.go
  x/ownership/internal/keeper/keeper.go
  x/ownership/internal/types/genesis.go
  x/process/genesis.go
  x/process/internal/keeper/keeper.go
  x/process/internal/types/genesis.go
  x/runner/genesis.go
  x/runner/internal/keeper/keeper.go
  x/runner/internal/types/genesis.go
  x/service/genesis.go
  x/service/internal/keeper/keeper.go
  x/service/internal/types/genesis.go
Labels: release:add

#1841 Fix dev-starter when user stop script during the first sleep of 5 sec
  scripts/dev-starter.sh
Labels: release:fix

#1844 Add a check in LCD client if the account exists or not
  cosmos/lcd.go
  cosmos/rpc.go
Labels: release:fix

#1853 Fix 3 issues with instance
  app/app.go
  instance/instance.pb.go
  protobuf/types/instance.proto
  x/instance/alias.go
  x/instance/client/rest/query.go
  x/instance/internal/keeper/keeper.go
  x/instance/internal/types/expected_keepers.go
  x/instance/internal/types/params.go
Labels: breaking change
